### ISSUE TITLE
Basic usage procedure

### ISSUE THREAD

**Issue by dpsanders** [bramtayl/PackageGenerator.jl#7]
Last time I used this package, I seem to remember I just had to do `generate("package_name")`.
Now that doesn't seem to work and I have no idea what to do...

**Comment by bramtayl** [comment]
Oh yeah, you'll need to run `configure` first. New feature

**Comment by dpsanders** [comment]
I get
```jl
julia> PackageGenerator.configure()
ERROR: MethodError: no method matching PackageGenerator.User()
Closest candidates are:
  PackageGenerator.User(::Any, ::Any; ssh_keygen_file, sync_time, travis_token, package_directory, authors, user_name) at /Users/davidsanders/.julia/v0.6/PackageGenerator/src/types.jl:12
  PackageGenerator.User(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Any) at /Users/davidsanders/.julia/v0.6/PackageGenerator/src/types.jl:2
Stacktrace:
 [1] #configure#17(::Array{Any,1}, ::Function) at /Users/davidsanders/.julia/v0.6/PackageGenerator/src/configure.jl:72
 [2] configure() at /Users/davidsanders/.julia/v0.6/PackageGenerator/src/configure.jl:72
```

**Comment by bramtayl** [comment]
See docs here: https://bramtayl.github.io/PackageGenerator.jl/latest/index.html#PackageGenerator.configure-Tuple. You'll need a github token and a travis token.

**Comment by dpsanders** [comment]
I see thanks, but
```
julia> travis_token = PackageGenerator.get_travis_token(github_token)
INFO: Getting travis token

ERROR: 405 Method Not Allowed: request method not allowed
```

**Comment by dpsanders** [comment]
(After defining `github_token`)

**Comment by dpsanders** [comment]
If in doubt, read the instructions... Sorry. (Need to check "scopes" when creating GitHub token.)

**Comment by bramtayl** [comment]
Wait so you're running into an issue with `get_travis_token` or was it fixed by checking the right scopes? If so it would great if you could help me debug.

**Comment by dpsanders** [comment]
Fixed by reading the instructions and checking those scopes, thanks.

**Comment by bramtayl** [comment]
Ok let me know if you have any more questions

**Comment by dpsanders** [comment]
All good for now, thanks. 
Sent a PR to add usage instructions to the README.
